endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  refresh:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 30
  client: 
    initialInstanceInfoReplicationIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
  server: 
    response-cache-update-interval-ms: 5000

ribbon: 
  serverListRefreshInterval: 1000

spring:
  rabbitmq:
    host: localhost
    port: 5672
    
eventBus:
  broker: redis
  redisHost: localhost #replace IP address here
  redisPort: 6379
  redisTopic: csrt-event-bus
  
logging:
  level:
    root: WARN
    com.amex: DEBUG
