
eureka:
  client:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
    
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  refresh:
    enabled: true
