spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tndavidson/config
        
server:
  port: 8888

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  
eureka:
  instance:
    hostname: config
      
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
