spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tndavidson/uname-webservice/shared/config
        
server:
  port: 8888

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  
  
eureka:
  instance:
    hostname: config
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      
spring:
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest