spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dbaugh/config
        
server:
  port: 8888

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  
eureka:
  instance:
    hostname: config
  client:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
    registerWithEureka: true
    fetchRegistry: true
      
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
