server:
  port: 8761

eureka:
  instance:
    hostname: discovery
    prefer-ip-address: true
    
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

spring.cloud.config.discovery.enabled: true

spring:
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest