server:
  port: 8080
  
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
  client:
    instance-info-replication-interval-seconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      
spring:
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
    
merchantLocator:
  redis:
    keyPrefix: "merchants:"
    
