server:
  port: 8080
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      
spring:
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest