
info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    uname: 
      path: /uname/**
      strip-prefix: true  
    merchant-locator:
      path: /merchant-locator/**
      strip-prefix: true
    service-manager:
      path: /service-manager/**
      strip-prefix: true
   
  
eureka:
  instance:
    hostname: router
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
  client:
    instance-info-replication-interval-seconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

spring:
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
      
router:
  serviceDiscoveryFilter:
    responseTimeThreshold: 140  
  