spring:
  profiles:
    active: cloud
---

spring:
  profiles: cloud
  
server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    hostname: uname
    nonSecurePort: 80
ribbon:
  eureka:
    enabled: true
    
---
spring:
  profiles: development
  
server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: false